### PR TITLE
added styling and fixed routes

### PR DESCRIPTION
**Pull request by hongmm**

### CODE REVIEW

**Comment by hongmm** [comment]
@Ahmed-Elawad @augustdolan @jw642459986 Anybody have time to check this? Probably done with styling for my proxy after this.

**Comment by jw642459986** [comment]
@hongmm do you have an image?

**Comment by hongmm** [comment]
image: 
image
image

**Comment by jw642459986** [comment]
@hongmm is it possible to make the position of production-options 'absolute', on the right side? That is how Ikea has it.

**Review by jw642459986 — APPROVED** [review]
looks good

**Pull request merged**
